# Description: Constants for auth http errors
USER_NOT_FOUND = "USER_NOT_FOUND"

# Register Errors
PASSWORDS_DO_NOT_MATCH = "PASSWORDS_DO_NOT_MATCH"
EMAIL_ALREADY_IN_USE = "EMAIL_ALREADY_IN_USE"
EMAIL_ALREADY_VERIFIED = "EMAIL_ALREADY_VERIFIED"

# Login Errors
INCORRECT_CREDENTIALS = "INCORRECT_CREDENTIALS"
NOT_VERIFIED = "NOT_VERIFIED"

# Auth Errors
INVALID_TOKEN = "INVALID_TOKEN"
