# Description: Constants for auth http codes
# Register Codes
USER_CREATED = "USER_CREATED"
EMAIL_VERIFIED = "EMAIL_VERIFIED"

# Login Codes
LOGGED_IN = "LOGGED_IN"
TOKEN_REFRESHED = "TOKEN_REFRESHED"
REFRESH_TOKEN_REVOKED = "REFRESH_TOKEN_REVOKED"
RECOVERY_EMAIL_SENT = "RECOVERY_EMAIL_SENT"
PASSWORD_CHANGED = "PASSWORD_CHANGED"
