CAMPAIGN_CREATED = "CAMPAIGN_CREATED"
CAMPAIGNS_RETRIEVED = "CAMPAIGNS_RETRIEVED"
CAMPAIGN_RETRIEVED = "CAMPAIGN_RETRIEVED"
CAMPAIGN_UPDATED = "CAMPAIGN_UPDATED"
CAMPAIGN_DELETED = "CAMPAIGN_DELETED"

CHARACTER_ADDED = "CHARACTER_ADDED"

PLAYER_INVITED = "PLAYER_INVITED"

ROLL_SUCCESSFUL = "ROLL_SUCCESSFUL"
