# Descripton: Constants for characters http codes
CHARACTER_CREATED = "CHARACTER_CREATED"
CHARACTERS_RETRIEVED = "CHARACTERS_RETRIEVED"
CHARACTER_RETRIEVED = "CHARACTER_RETRIEVED"

CHARACTER_UPDATED = "CHARACTER_UPDATED"
